### ISSUE TITLE
building and packaging in mac OS X 10.11.5 ElCapitan

### ISSUE THREAD

**Issue by sambitdixit** [Stratio/Crossdata#573]
Hi,
I have cloned the git repo and followed instructions as in Stratio documentation to create packages. 
I have installed following pre-requisites using home-brew before running 1 and 2 commands below 
a)fakeroot
b)dpkg
c)rpm
d)debianutils
e)gnu-tar 
  
1. mvn clean install -DskipUTs -DskipITs
2. mvn package -Ppackage -DskipUTs -DskipITs

Im getting below error while running the second command above i.e. mvn package -Ppackage -DskipUTs -DskipITs

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Stratio Crossdata Parent ........................... SUCCESS [  0.697 s]
[INFO] Core ............................................... SUCCESS [ 18.055 s]
[INFO] Cassandra Connector ................................ SUCCESS [  5.932 s]
[INFO] MongoDB Connector .................................. SUCCESS [  4.087 s]
[INFO] Elasticsearch Connector ............................ SUCCESS [  8.613 s]
[INFO] Common ............................................. SUCCESS [  3.165 s]
[INFO] Server ............................................. SUCCESS [ 17.380 s]
[INFO] Driver ............................................. SUCCESS [ 16.199 s]
[INFO] Streaming .......................................... SUCCESS [ 17.463 s]
[INFO] TestsIT ............................................ SUCCESS [  0.066 s]
[INFO] Dist ............................................... FAILURE [  2.083 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:34 min
[INFO] Finished at: 2016-06-09T16:18:22+05:30
[INFO] Final Memory: 137M/1431M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.stratio.mojo.unix:unix-maven-plugin:1.2.0:package-deb (deb) on project dist_2.10: Unable to create package. Command 'fakeroot' returned a non-null exit code: 2 -> [Help 1]

**Comment by miguel0afd** [comment]
Hi @sambitdixit,

could you run the command "mvn **-X** package -Ppackage -DskipUTs -DskipITs" in order to get a verbosity output of Maven, please?

**Comment by miguel0afd** [comment]
Support for Mac OS X has been deprecated. Docker images can be used instead: https://hub.docker.com/r/stratio/crossdata-scala211/
