### ISSUE TITLE
VIEW IS NOT SHOWED AS RESULT "SHOW TABLES"

### ISSUE THREAD

**Issue by maguilarstratio** [Stratio/Crossdata#781]
Crossdata Version: 1.6.0
Persistence: Cassandra
Query: " CREATE VIEW viewName AS SELECT columnName from TABLE"

View is created permanently , because after closing crossdata conection it is possible a query about the view created previously, but the viewName is not showed with "SHOW TABLES".

**Comment by miguel0afd** [comment]
Hi @maguilarstratio,

a JIRA ticket has been created to fix this issue: https://stratio.atlassian.net/browse/CROSSDATA-830

Thanks for the feedback
